account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
app_name = "account"
urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='registration/login.html'),
         name='login'),
    path('register/', views.register, name='register'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='registration/logged_out.html'), name='logout'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             template_name='registration/password_change_form.html'),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),
    # # restore password urls
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_form.html'),
         name='password-reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('edit/', views.edit, name='edit'),
]

pinclone/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('pinterest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# the Django development server will be in charge of serving the media files during development.
# The static() helper function is suitable for development 
# but not for production use. Never serve your static files with Django in a production environment.

pinterest/urls.py
from django.urls import path

from . import views

app_name = "pinterest"

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like_image/', views.like_image, name='like_image'),
    path('delete/<int:id>/', views.delete_image, name='delete_image'),
    path('my_post/', views.my_post, name='my_post'),
    path('user_post/<int:user_id>/', views.my_post, name='user_post'),
    path('', views.index, name='index'),
]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(
        blank=True,
   
        null=True
    )
    photo = models.ImageField(
        upload_to='users/%Y/%m/%d',
        blank=True
    )

    def __str__(self):
        return 'Profile for user {0}'.format(self.user.username)

account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    """
    Form to allow the user to edit their first_name,
    last_name, and email.
    """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    """
    Form to let the user edit his profile. This is
    extra data saved in custom Profile model.
    """

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import (
    LoginForm, UserRegistrationForm, UserEditForm,
    ProfileEditForm
)
from .models import Profile


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                    username=cd['username'],
                    password=cd['password']
                )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()

    return render(request, 'account/login.html', {
        'form': form
    })


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()

            # an empty profile is created associated with
            # the user
            profile = Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {
                'new_user': new_user
            })
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {
        'user_form': user_form
    })


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {
        'section': 'dashboard'
    })


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated '
                                      'successfully')
        else:
            messages.error(request, 'Error updating your'
                                    ' profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'account/edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-social.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
        crossorigin="anonymous">

    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    {% block styleblock %}
    {% endblock %}
</head>
<body>
    <div id="" style="padding-bottom:3em; padding-top:2em; margin-left: 0em;">
        {% include 'nav.html' %}
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="{{message.tags}}">
                    {{message|safe}}
                    <a href="#" class="close">✖</a>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div id="content" >
  
        {% block content %}
        {% endblock %}
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function(){
        $('a.close').click(function (e) {
            console.log(e);
            e.preventDefault();
            $('ul.messages').hide()
        });
    });
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</html>

account/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light;" style = "background-color: rgb(235, 216, 209);" >
    <a class="navbar-brand" style= "color: brown; font-size: xx-large; padding-bottom: .3em ;" href="{% url 'pinterest:index' %}"><b>Pinterest</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if index == 'Home' %}active{% endif %}">
                <a class="nav-link" style = "font-size: x-large; padding-top: .3em; " href="{% url 'pinterest:index' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item {% if my_post == 'My Posts' %}active{% endif %}">
                <a class="nav-link" style = " padding-top: 1em " href="{% url 'pinterest:my_post' %}">My Posts</a>
            </li>

            <li class="nav-item {% if create == 'New Post' %}active{% endif %}">
                <a class="nav-link disabled" style = " padding-top: 1em " href="{% url 'pinterest:create' %}">New Post</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" style = " padding-top: 1em " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{user}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item btn btn-success" style = " padding-top: 1em " href="{% url 'account:logout' %}">Sign Out</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item" >
                <a class="nav-link disabled" style = " padding-top: 1em;  " href="{% url 'account:login' %}">Sign in</a>
            </li>
            <li class="nav-item" >
                <a class="nav-link disabled" style = " padding-top: 1em " href="{% url 'account:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
   
   
</div>
</nav>