account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
app_name = "account"
urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='registration/login.html'),
         name='login'),
    path('register/', views.register, name='register'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='registration/logged_out.html'), name='logout'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             template_name='registration/password_change_form.html'),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),
    # # restore password urls
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_form.html'),
         name='password-reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('edit/', views.edit, name='edit'),
]

pinclone/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('pinterest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# the Django development server will be in charge of serving the media files during development.
# The static() helper function is suitable for development 
# but not for production use. Never serve your static files with Django in a production environment.

pinterest/urls.py
from django.urls import path

from . import views

app_name = "pinterest"

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like_image/', views.like_image, name='like_image'),
    path('delete/<int:id>/', views.delete_image, name='delete_image'),
    path('my_post/', views.my_post, name='my_post'),
    path('user_post/<int:user_id>/', views.my_post, name='user_post'),
    path('', views.index, name='index'),
]

pinterest/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Pin(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='pins_created',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True, default='')
    created = models.DateField(auto_now_add=True, db_index=True)

    user_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='images_liked',
        blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Pin, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pinterest:detail', args=[self.id, self.slug])

    def __str__(self):
        return self.title

pinterest/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify


from .models import Pin


default_img = 'http://saveabandonedbabies.org/wp-content/uploads/2015/08/default.png'


class PinCreateForm(forms.ModelForm):
    class Meta:
        model = Pin

        fields = ('title', 'url')

    def clean_url(self):
        if self.cleaned_data['url']:
            url = self.cleaned_data['url']
        else:
            url = default_img
        print('url:', url)

        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid \
                            image extensions')
        return url

    def save(self, force_insert=False, force_update=False, commit=False):
        image = super(PinCreateForm, self).save(commit=False)
        if self.cleaned_data['url'] is None:
            image_url = default_img
        else:
            image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # download image from the given URL
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)

        if commit:
            image.save()
        return image

pinterest/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth.models import User

from .models import Pin
from .forms import PinCreateForm


def index(request):
    images = Pin.objects.all().order_by('-created')
    return render(request, 'pinterest/index.html', {
                'images': images,
                'index': 'Home'
        })


def my_post(request, user_id=None):
    context = {}
    if user_id:
        user = User.objects.get(id=user_id)
        images = Pin.objects.filter(user=user).order_by('-created')
        message = "Pinned images"
    else:
        user = request.user
        images = Pin.objects.filter(user=user).order_by('-created')
        message = "Your pinned images"
        context["my_post"] = 'My Posts'

    context["images"] = images
    context["message"] = message
    return render(request, 'pinterest/index.html', context)


# @login_required
def image_create(request):
    if request.method == 'POST':

        form = PinCreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            return redirect('pinterest:my_post')

    else:
        form = PinCreateForm()
    return render(request, 'pinterest/pin/create.html', {
        'section': 'images',
        'form': form,
        'create': 'New Post'
    })


def delete_image(request, id):
    pin = get_object_or_404(Pin, id=id)
    pin.delete()
    return redirect("pinterest:my_post")


def like_image(request):
    user = request.user
    id = request.POST.get('id')
    action = request.POST.get('action')
    if id and action:
        pin = Pin.objects.get(id=id)
        if action == "like":
            pin.user_like.add(user)
        else:
            pin.user_like.remove(user)
        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ko'})

pinterest/templates/pinterest/index.html
{% extends "base.html" %} {% load static %} {% block title %} {% endblock %} {% block content %} {% if request.user.is_authenticated %}
<h1>Pined Images</h1>
<br>
<div class="container">
    <div class="gallery">
        {% for image in images %}
        <div class="card">
            <div class="card-header">
                <div class="gallery-item" tabindex=0>
                    <img src="{{image.url}}" class="gallery-image" alt="">
                </div>
            </div>
            <div class="card-body">
                <p class="card-text mb-2">{{image.title}}</p>
                <p class="card-text"><i class="far fa-clock pr-2"></i>{{image.created}}</p>
                <p class="card-text">by <strong><a
              href="{% url "pinterest:user_post" image.user.id %}">{{image.user}}</a></strong></p>
                <p>{{image.description}}</p>
            </div>
            <div class="card-footer">
                <a href="#" class="like float-right" id="image-{{image.id}}" data-id="{{ image.id }}" data-action="{% if request.user in image.user_like.all %}un{% endif %}like">
          {% if request.user not in image.user_like.all %}
          Like
          {% else %}
          Unlike
          {% endif %}
        </a> {% if request.user == image.user %}
                <a href="{% url 'pinterest:delete_image' image.id %}"><i class="far fa-trash-alt float-right my-1 mr-3"></i></a> {% endif %}
                <span id="count-{{image.id}}" class="count">
          {{image.user_like.count}}
        </span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div>
    <center style= " font-size: x-large; font-style: italic; text-align: center;">If you are looking for inspiration to create the life you love <br> please <a href="{% url 'account:login' %}">Sign in.</a></center>
</div>
{% endif %}
<script>
    function getCookie(c_name) {
        if (document.cookie.length > 0) {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1) {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start, c_end));
            }
        }
        return "";
    }

    $('a.like').click((e) => {
        e.preventDefault();
        let dataset = Object.assign({}, e.target.dataset);
        let id = dataset['id']
        let action = dataset['action']
        console.log(id, action)
        $.ajax({
                url: '{% url "pinterest:like_image" %}',
                method: 'POST',
                data: {
                    id: id,
                    action: action
                },
                headers: {
                    "X-CSRFToken": getCookie("csrftoken")
                }
            })
            .then((response) => {
                if (response['status'] == 'ok') {
                    var previous_action = $('#image-' + id).data('action')
                        // toggle data-action
                    $('#image-' + id).data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('#image-' + id).text(previous_action == 'like' ? 'Unlike' : 'Like');

                    // update total likes
                    var previous_likes = parseInt($('#count-' + id).text());
                    $('#count-' + id).text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
            })
            .catch((error) => {
                console.log(error)
            })
    });
</script>
{% endblock %}